language: node_js
node_js:
  - stable
cache:
  directories:
    - node_modules
    - frontend/node_modules
install:
  - npm install
  - cd frontend && npm install
script:
  - npm test
  - npm test --prefix frontend
  - npm run build
